name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/oracle/oraclelinux8-ruby:3.3

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf groupinstall -y 'Development Tools'
          dnf install -y git nodejs
          gem install bundler

      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gems-${{ runner.os }}-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build Slate project
        run: bundle exec middleman build
